\set ON_ERROR_STOP on
\getenv owner_password MIGRATION_PASSWORD
\getenv app_password APP_DATABASE_PASSWORD

CREATE ROLE zazie_owner LOGIN PASSWORD :'owner_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE zazie_app LOGIN PASSWORD :'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE zazie OWNER zazie_owner;

\connect zazie
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CREATE, USAGE ON SCHEMA public TO zazie_owner;
GRANT CONNECT ON DATABASE zazie TO zazie_app;
