import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { z } from 'zod';
import {
  EvaluationInputSchema,
  EvaluationReportSchema,
  HypothesisPackSchema,
} from '../src/contracts.js';

const definitions = [
  ['evaluation-input.v1.json', EvaluationInputSchema],
  ['evaluation-report.v1.json', EvaluationReportSchema],
  ['hypothesis-pack.v1.json', HypothesisPackSchema],
] as const;

await mkdir(new URL('../schemas/', import.meta.url), { recursive: true });
for (const [name, definition] of definitions) {
  const schema = z.toJSONSchema(definition, { target: 'draft-2020-12' });
  const output =
    JSON.stringify(
      {
        ...schema,
        $id: `https://raw.githubusercontent.com/RomainGratier/zazie/main/schemas/${name}`,
        $comment:
          'Generated by npm run schemas. The TypeScript runtime additionally checks serialization limits, unique IDs, and Choice probability consistency; JSON Schema cannot express all cross-field invariants.',
      },
      null,
      2,
    ) + '\n';
  const path = new URL(`../schemas/${name}`, import.meta.url);
  if (process.argv.includes('--check')) {
    if ((await readFile(path, 'utf8')) !== output)
      throw new Error(`Schema is stale: ${name}. Run npm run schemas.`);
  } else {
    await writeFile(path, output);
  }
}
